title: Slime

description: >
  An Elixir library for rendering Slim-like templates.

baseurl: ""
url: "http://slime-lang.com"

github_username: slime-lang

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - mix.exs
  - mix.lock
  - CNAME
  - README.md
  - deps
  - _build
