# Site settings
title: Slime
description: >
  An Elixir library for rendering Slim-like templates.
baseurl: ""
url: "https://slime-lang.github.io" # the base hostname & protocol for your site
github_username: slime-lang

# Build settings
markdown: kramdown
